# permissions for end users to view vpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aws-vpc
    app.kubernetes.io/part-of: aws-vpc
    app.kubernetes.io/managed-by: kustomize
  name: vpc-viewer-role
rules:
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - vpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - vpcs/status
  verbs:
  - get
